server:
  port: 8101 #运行端口号
spring:
  application:
    name: user-service #服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  zipkin: #收集日志的zipkin-server
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0 #设置Sleuth的抽样收集概率
eureka:
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8001/eureka/ #配置注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always