server:
  port: 8904
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/renlong56/spring-cloud-config.git
#          default-label: master
          search-paths: '{application}'
#          strict-host-key-checking: false
          username: renlong56
          password: rei140703
          clone-on-start: true #开启启动时直接从git获取配置
#          ignoreLocalSshSettings: false
#  security:  #开启用户密码验证
#    user:
#      name: root
#      password: root
  rabbitmq: #rabbitmq相关配置
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'